### ISSUE TITLE
代码框背景高亮问题

### ISSUE THREAD

**Issue by LXTlogic** [jinghu-moon/typora-see-yue-theme#15]
在新版主题下，当前编辑行得背景高亮显示白条较为不和谐，虽然可以在css文件中可以改为代码框背景色，但仍建议默认是代码框背景色而非是白色
1.3.3：
![屏幕截图 2022-08-21 141257](https://user-images.githubusercontent.com/75785634/185778148-2a9dbc4f-86af-4ba8-9364-c947ba6b11e4.png)
1.3.2：
![屏幕截图 2022-08-21 141547](https://user-images.githubusercontent.com/75785634/185778250-b915ecfa-f3b4-451d-b364-0b10cceea5a5.png)

**Comment by jinghu-moon** [comment]
好的，下个版本修复。

**Comment by jinghu-moon** [comment]
See Yue v1.4 已发布，请及时更新。
