### ISSUE TITLE
导出为html问题

### ISSUE THREAD

**Issue by gjjcommon** [jinghu-moon/typora-see-yue-theme#17]
使用see-yue主题后 将markdown文档导出为html文件 在浏览器浏览该html页面的时候 不可以上下滑动内容 其他主题可以

**Comment by jinghu-moon** [comment]
v1.3.3 已经修复。

**Comment by gjjcommon** [comment]
> v1.3.3 已经修复。请及时更新版本。
> 
> 下载链接： https://github.com/jinghu-moon/typora-see-yue-theme/releases/tag/v1.3.3

ok了  🐂的 👍🏻
