### ISSUE TITLE
标题等级提示无法关闭

### ISSUE THREAD

**Issue by gjjcommon** [jinghu-moon/typora-see-yue-theme#18]
下载主题是在这里下载的 https://theme.typora.io/theme/see-yue/
看了代码仓库里的md文档了 但是 说是在headline.css的208-271行 但是这个文件只有260多行  而且没有md文档里说的字段

**Comment by jinghu-moon** [comment]
在 `root-elemet.css` 选择是否开启。关键词：**--headline-rating-prompt-state**

**Comment by jinghu-moon** [comment]
我想国修改写官方网站上我的主题介绍文档，但是官方通过 PR 的速度太慢了，就懒得 PR 更新内容了。🙃

**Comment by gjjcommon** [comment]
> 我想过修改写官方网站上我的主题介绍文档，但是官方通过 PR 的速度太慢了，就懒得 PR 更新内容了。🙃

我按照你说的操作 可以了  这个主题是我用过的最完美的  马上手动Star  🐂 真🐂

**Comment by jinghu-moon** [comment]
谢谢夸奖啊。 😉

**Comment by zyjdmmm** [comment]
我更新后也找到了
