### ISSUE TITLE
icon打开开关未找到

### ISSUE THREAD

**Issue by gjjcommon** [jinghu-moon/typora-see-yue-theme#21]
如链接 https://github.com/jinghu-moon/typora-see-yue-theme/blob/main/%E4%B8%BB%E9%A2%98%E8%AF%B4%E6%98%8E%EF%BC%88%E5%BF%85%E7%9C%8B%EF%BC%89.md#148-%E7%BD%91%E7%AB%99%E9%93%BE%E6%8E%A5%E6%98%BE%E7%A4%BA%E5%AF%B9%E5%BA%94%E5%9B%BE%E6%A0%87 所说的 未找到打开icon的做法

目前css文件里是这样的
a::before {
  display          : inline-block;
  position         : relative;
  background-repeat: no-repeat;
  background-size  : 1.1em 1.1em;
  top              : 0.2em;
  width            : 1.1em;
  height           : 1.1em;
  margin-right     : 0.2em;
}

但是icon没打开 需要如何打开呢

**Comment by jinghu-moon** [comment]
要在 `see-yue.css` 开头取消 `favicon.css` 的注视
```css
/* 网页logo */
/* @import "./SeeYue/CSS/favicon.css"; */
```

**Comment by gjjcommon** [comment]
好的好的
