### ISSUE TITLE
代码块语言选择 c++，右上角显示为 C#

### ISSUE THREAD

**Issue by Timmiy** [jinghu-moon/typora-see-yue-theme#22]
![image](https://user-images.githubusercontent.com/15071973/188313166-6721c965-cb7d-4d16-9162-478730e1764b.png)

**Comment by jinghu-moon** [comment]
请更新至最新版本，新版本已修复

**Comment by jinghu-moon** [comment]
See Yue v1.4 已发布，请及时更新。
