### ISSUE TITLE
文档标题和内容会有重叠的情况

### ISSUE THREAD

**Issue by gjjcommon** [jinghu-moon/typora-see-yue-theme#24]
![die](https://user-images.githubusercontent.com/47707408/193217092-231f34d6-76f9-435c-9513-76acb5fe5bc0.png)

**Comment by gjjcommon** [comment]
上图中黑色字体是markdown文档的文件名 显示在文件最上方 会跟内容有重叠 是否可以加个底色 覆盖下 其实是可用的 优化下 感觉视觉上会更好

**Comment by jinghu-moon** [comment]
你用的是 Mac？win 上没有这种情况。下图是 win 的界面

![](https://s3.bmp.ovh/imgs/2022/09/30/a0f5e2c3e86b4b3b.png)

可以提供下示例文件吗？

**Comment by gjjcommon** [comment]
嗯嗯 是的 mac的 这个应该是一个偶现的问题 刚才又看 好像好了  我再看看哈 如果不再出现 我来close  如果出现了 我把响应的内容反馈出来  谢谢

**Comment by jinghu-moon** [comment]
估计是 typora 界面加载有误。
