### ISSUE TITLE
侧边栏文件页

### ISSUE THREAD

**Issue by cfikt** [jinghu-moon/typora-see-yue-theme#27]
在侧边栏点击文件时，自动跳转到顶部

**Comment by cfikt** [comment]
已经是1.3.3最新版， #7 上的方法不能解决该问题

**Comment by cfikt** [comment]
![see yue](https://user-images.githubusercontent.com/109979597/200823728-2f48db6d-08fb-4950-87df-96f8b6302d88.gif)
![other](https://user-images.githubusercontent.com/109979597/200823753-67c32187-a751-4ad5-bec5-7dc8146ef2b1.gif)

**Comment by cfikt** [comment]
第一个gif文件为 see yue 主题，当点击一个文件时，会自动跳转到文件侧边栏的顶部
第二个gif文件是其它主题，当点击一个文件时，文件侧边栏是固定的（除了 see yue 的其它主题都是如此）

**Comment by jinghu-moon** [comment]
测试了下，v1.3.3 版本没有这个问题。我问了用这个主题的朋友，他也没有遇到。我觉得可能是你自己改的代码造成的。可以在 `sidebar.css` 里注释掉所有的 **transition** 属性，或许可以解决这个问题。

**Comment by cfikt** [comment]
为了验证是否又我修改代码导致该问题，我把seeyue.css以及seeyue文件夹删了，并且在github重新下载，该问题依然存在

**Comment by jinghu-moon** [comment]
难道是 Typora 版本问题？我的版本是 1.4.8。以前也有老哥遇到过 bug，怎么排查都找不到，最后升级 Typora 版本就好了。

**Comment by cfikt** [comment]
我也不知道该问题出现在哪，因为我的tyoira版本也是最新版1.4.8

**Comment by cfikt** [comment]
不知道这段代码有何作用，我把它全部注释了，这个问题解决了
![image](https://user-images.githubusercontent.com/109979597/200895375-c7d1e6ae-6f3d-499c-9db6-5927ae67a1cd.png)

**Comment by cfikt** [comment]
准确来说是这一段，注释了后问题得到解决，但是文件目录层级线没有了
![image](https://user-images.githubusercontent.com/109979597/200896540-802ef24f-b4f4-4a7a-b777-4c4c6d5930ce.png)

**Comment by jinghu-moon** [comment]
好吧，有点奇怪。
```css
/* 给文件层级线提供定位 */
.file-node-expanded>.file-node-children:not(:only-child) {
  position   : relative;
  margin-left: 10px;
  display    : block;
} 
```

试试把 `.file-node-expanded>.file-node-children:not(:only-child)` 改为 `:not(.file-node-root).file-node-expanded[data-is-directory="true"]>.file-node-children:not(:only-child)` 看看，能不能解决这个问题 。

下个版本 v1.4，代码进行了重构，或许可以解决这个问题。

**Comment by cfikt** [comment]
.file-node-expanded>.file-node-children:not(:only-child) 改为 :not(.file-node-root).file-node-expanded[data-is-directory="true"]>.file-node-children:not(:only-child)  这不能解决该问题

**Comment by cfikt** [comment]
这里再提交一个问题，使用typora中的替换后，代码块会变成这样，要重启typora才能恢复
![image](https://user-images.githubusercontent.com/109979597/201016650-f5331192-6616-412a-ae1f-f3741e9484a5.png)

**Comment by jinghu-moon** [comment]
> 这里再提交一个问题，使用typora中的替换后，代码块会变成这样，要重启typora才能恢复 ![image](https://user-images.githubusercontent.com/109979597/201016650-f5331192-6616-412a-ae1f-f3741e9484a5.png)

经测试，这个问题在部分主题上存在。 v1.4 尝试修复。

**Comment by jinghu-moon** [comment]
> .file-node-expanded>.file-node-children:not(:only-child) 改为 :not(.file-node-root).file-node-expanded[data-is-directory="true"]>.file-node-children:not(:only-child) 这不能解决该问题

好吧，v1.4 版本发布了，你尝试下吧。目前实在是定位不到问题所在。😑

**Comment by jinghu-moon** [comment]
> 这里再提交一个问题，使用typora中的替换后，代码块会变成这样，要重启typora才能恢复 ![image](https://user-images.githubusercontent.com/109979597/201016650-f5331192-6616-412a-ae1f-f3741e9484a5.png)

确定是要重启 Typora 才可以吗？如果是一个一个替换的话，代码块高亮、缩进不会失效；全部替换的话，代码块高亮、缩进才会失效，全部替换完，只要光标定位在代码块内，代码块高亮、缩进立即恢复。

我测试了大部分主题，全部替换都会出现这种问题。这应该是 Typora 的问题。与主题无关

**Comment by jinghu-moon** [comment]
See Yue v1.4 已发布，请及时更新。
