### ISSUE TITLE
icon不生效

### ISSUE THREAD

**Issue by lichaoii** [jinghu-moon/typora-see-yue-theme#29]
反复试过多次，没生效
![image](https://user-images.githubusercontent.com/66879965/202238712-ddc860d3-0ec9-4651-8deb-7ec5948fe158.png)

**Comment by jinghu-moon** [comment]
主题是最新版本吗，最新版本是 v1.3.3。

最新版本使用 icon 需要以下操作。
```css
/* 取消下面代码的注释 */
/* 网页logo */
/* @import "./SeeYue/CSS/favicon.css"; */
```

**Comment by jinghu-moon** [comment]
使用 v1.3.3 版本，按照上面的方法测试了下，是可以的。

**Comment by lichaoii** [comment]
> 使用 v1.3.3 版本，按照上面的方法测试了下，是可以的。

感谢回复，按照方法成功了！
