### ISSUE TITLE
能否在夜间模式实现图片亮度的降低

### ISSUE THREAD

**Issue by hengxingstu** [jinghu-moon/typora-see-yue-theme#31]
在夜间模式浏览tpyora的图片亮度会比其他部分高很多，特别是一些纯白背景的图片。能否实现一个自动套一层蒙版来降低亮度的功能

**Comment by hengxingstu** [comment]
copy that.希望早日更新

**Comment by jinghu-moon** [comment]
v1.4 版本预计会在 4 月底发布。这是一个大更新。😉
