### ISSUE TITLE
文本马克笔涂抹效果出不来

### ISSUE THREAD

**Issue by Zero-Yi7** [jinghu-moon/typora-see-yue-theme#32]
1.4.5 文本马克笔涂抹效果，出不来效果。查看了相关代码 `code-snippet.css` 文件的 187 到 196 行，并未注释掉。请问还有其他什么原因吗？

**Comment by jinghu-moon** [comment]
刚测试了下主题最新版本 v1.3.3，是可以实现的。我的 typora 版本是 1.5.8。难道是 typora 版本问题？

**Comment by Zero-Yi7** [comment]
已经解决了，原因是偏好设置中的 Markdown 扩展语法“高亮”选项没有打开，抱歉因为这么基础的原因打扰了你。
另外，我发现缩放图片功能失效了，使用的主题最新版本 v1.3.3，切换了默认主题 Github 后图片是以缩放后的效果展示的，而 See Yue 主题没有效果。

**Comment by jinghu-moon** [comment]
图片缩放问题解决方法如下：

`root-element.css` 文件，搜索关键词 **--image-size**，将对应值改为 **auto** 即可。如下：
```css
--image-size: auto
```
#13 ，已说明解决方法

**Comment by jinghu-moon** [comment]
See Yue v1.4 已发布，请及时更新。
