### ISSUE TITLE
怎么切换see yue主题

### ISSUE THREAD

**Issue by MiaoAA-Hello** [jinghu-moon/typora-see-yue-theme#34]
怎么切换主题
See Yue Light — 浅色主题

See Yue Soft — 护眼主题

See Yue Dark — 深色主题

**Comment by jinghu-moon** [comment]
目前为止 SeeYue 主题 v1.4 还在开发中，预计在 4 月底发布。

**Comment by MiaoAA-Hello** [comment]
了解


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jinghu-moon/typora-see-yue-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jinghu-moon/typora-see-yue-theme] 怎么切换see yue主题 (Issue #34)





 
目前为止 SeeYue 主题 v1.4 还在开发中，预计在 4 月底发布。

**Comment by yushengjiaohuang** [comment]
马上5月了……

**Comment by jinghu-moon** [comment]
> 马上5月了……

感谢你对  See Yue 主题的关注，代码可以在 04 月 30 号完成，但我还需要半天左右时间整理文档。即 05 月 01 号正式发布。

PS：作者准备考研，时间确实不够用。 ：(

**Comment by jinghu-moon** [comment]
See Yue v1.4 已发布，请及时更新。
