### ISSUE TITLE
1.4 版本主题侧边栏导航无法移动到指定位置

### ISSUE THREAD

**Issue by dselegent** [jinghu-moon/typora-see-yue-theme#37]

**Comment by dselegent** [comment]
![GIF 2023-5-2 11-40-01](https://user-images.githubusercontent.com/70082666/235574658-c9994abe-d09e-434f-af2a-7805e0c0cfd0.gif)

**Comment by jinghu-moon** [comment]
怎么触发的，快速点击不同标题吗？

**Comment by jinghu-moon** [comment]
是不是先点击一个标题 A，页面还没有跳转到这个标题所在区域的时候，再次点击标题 B，页面没有跳转到标题 B，只停留在 标题 A。如果是这样的话，这不是主题问题。应该是 Typora 的问题。

**Comment by dselegent** [comment]
> 是不是先点击一个标题 A，页面还没有跳转到这个标题所在区域的时候，再次点击标题 B，页面没有跳转到标题 B，只停留在 标题 A。如果是这样的话，这不是主题问题。应该是 Typora 的问题。

没有，我没有快速点击

**Comment by dselegent** [comment]
![GIF 2023-5-2 12-37-48](https://user-images.githubusercontent.com/70082666/235580511-336c6843-f0c3-4961-9bc2-327abd07b068.gif)

**Comment by dselegent** [comment]
> ![GIF 2023-5-2 12-37-48](https://user-images.githubusercontent.com/70082666/235580511-336c6843-f0c3-4961-9bc2-327abd07b068.gif) [ ![GIF 2023-5-2 12-37-48](https://user-images.githubusercontent.com/70082666/235580511-336c6843-f0c3-4961-9bc2-327abd07b068.gif) ](https://user-images.githubusercontent.com/70082666/235580511-336c6843-f0c3-4961-9bc2-327abd07b068.gif) [ ](https://user-images.githubusercontent.com/70082666/235580511-336c6843-f0c3-4961-9bc2-327abd07b068.gif)

这次侧边栏过去了，但是右侧没有移动到对应位置

**Comment by dselegent** [comment]
![GIF 2023-5-2 12-41-02](https://user-images.githubusercontent.com/70082666/235580835-291dcbbc-95e5-4730-b6df-5ede231632e6.gif)
我使用自带的github主题点快点也没问题

**Comment by dselegent** [comment]
> 怎么触发的，快速点击不同标题吗？

就是刚进来这个文档，随便点一个标题会跳转到对应的位置，这时点一个刚才点击的标题之前的标题就会出问题了

**Comment by dselegent** [comment]
我发现问题了，确实和你说的一样的，这个主题快速点击标题就会出问题，隔那么一两秒就正常了，自带的那些主题快速点击没问题

**Comment by jinghu-moon** [comment]
outline.css 搜索下面代码，注释
```css

transition    : background-color .3s ease;

```

这样应该可以解决。

这句代码本意是为了美观。不快速点击，基本触发不了。你可以慢点点击。

**Comment by dselegent** [comment]
感谢

**Comment by jinghu-moon** [comment]
问题解决了吗？

**Comment by dselegent** [comment]
> 所有者



> outline.css 搜索下面代码，注释
> 
> ```css
> transition    : background-color .3s ease;
> ```
> 
> 这样应该可以解决。
> 
> 这句代码本意是为了美观。不快速点击，基本触发不了。你可以慢点点击。



> 问题解决了吗？

解决了，刚才改错文件了，改的是我下载的文件
