### ISSUE TITLE
1.4版本关于目录的问题

### ISSUE THREAD

**Issue by Aurora-kite** [jinghu-moon/typora-see-yue-theme#43]
> **系统**：win10
> **主题版本**：1.4
> **时间**：2023.6.6

**问题**：如果打开的页面缩小（即宽度变小），目录的内容会自动跳到下一行，然而右边还有很大的空间
这是正常的：
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/bdd46193-b805-4528-a95b-103b6715cc1d)

当我缩小页面宽度时：
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/c05df51b-6773-4da1-b995-21a49252803c)

当我进一步缩小页面宽度时：
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/dcee3ac4-e7b3-416f-988c-e7c85073f2d2)
如图所示，右边还有较大的空间
**需求**：我希望我可以设置这个蓝色框框内的范围，比如页面缩短到多少长度时会进行换行

**Comment by jinghu-moon** [comment]
抱歉，最近在忙着考试，没看到 issues。

`xxxx-configs.css` 提供了修改目录标题透明边框的代码，如下：

```css
  /* ======================== 其他设置 ======================== */
  /* 正文目录标题悬浮背景颜色 */
  --hover-contents-headline-bg-color    : #fff;
  /* 增大一级标题 tab 的宽度，开发者习惯一级标题用一个 Tab 距离分隔章节和章节名 */
  --contents-h1-tab-space               : 2px transparent solid;
  /* 1 ~ 6 级标题右侧透明边框，扩大用户可点击范围，使用 border-right 实现 */
  --contents-h1-click-right-border-width: 370px;
  --contents-h2-click-right-border-width: 400px;
  --contents-h3-click-right-border-width: 340px;
  --contents-h4-click-right-border-width: 300px;
  --contents-h5-click-right-border-width: 250px;
  --contents-h6-click-right-border-width: 220px;
```

此代码是为了增加标题的点击范围。标题过长，就会出现你提到的情况。

**Comment by Aurora-kite** [comment]
> 



> 抱歉，最近在忙着考试，没看到 issues。
> 
> `xxxx-configs.css` 提供了修改目录标题透明边框的代码，如下：
> 
> ```css
>   /* ======================== 其他设置 ======================== */
>   /* 正文目录标题悬浮背景颜色 */
>   --hover-contents-headline-bg-color    : #fff;
>   /* 增大一级标题 tab 的宽度，开发者习惯一级标题用一个 Tab 距离分隔章节和章节名 */
>   --contents-h1-tab-space               : 2px transparent solid;
>   /* 1 ~ 6 级标题右侧透明边框，扩大用户可点击范围，使用 border-right 实现 */
>   --contents-h1-click-right-border-width: 370px;
>   --contents-h2-click-right-border-width: 400px;
>   --contents-h3-click-right-border-width: 340px;
>   --contents-h4-click-right-border-width: 300px;
>   --contents-h5-click-right-border-width: 250px;
>   --contents-h6-click-right-border-width: 220px;
> ```
> 
> 此代码是为了增加标题的点击范围。标题过长，就会出现你提到的情况。

![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/96c009cf-26df-409f-8773-e8f68115bb9d)
问题目前得到解决🌹

**Comment by jinghu-moon** [comment]
好的
