### ISSUE TITLE
关于代码块颜色高亮的问题

### ISSUE THREAD

**Issue by Aurora-kite** [jinghu-moon/typora-see-yue-theme#44]
> **系统**：win10
> **主题版本**：1.4
> **时间**：2023.6.6

**问题①**：如图所示，在使用mermaid时，对于注释的时间也进行了高亮（pure和salt皆如此,而且那个8是黑色，其他数字是蓝色）
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/cc632f7d-a9d1-40b7-bf45-b46c0ccaeafb)
以及暗黑模式下
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/f29b42f1-a02e-4c19-a7b8-dece9b176ceb)

**问题②**
同一种语言，三行注释，三种颜色🤔
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/0393aea5-caac-4c96-8b90-f911169bfed1)

**需求**：我希望注释的内容不进行高亮，或者数字全部高亮（可选）

**Comment by jinghu-moon** [comment]
这与主题使用的代码配色和 Typora 自己使用的代码高亮语法有关。修改是比较麻烦的。可能你修改了这里，在别的编程语言里又出现了问题。

或许你可以考虑换个代码配色，看看有没有让你满意的。更换主题代码配色的步骤如下：

1. 访问 [CodeMirror: Theme Demo](https://codemirror.net/5/demo/theme.html) ，选择符合自己的主题。（以 nord 主题为例）
2. 下载主题代码文件 <https://codemirror.net/5/codemirror.zip> （**code-block** 文件夹已下载）
3. 打开 `nord.css` ，将代码内关键字 `nord` 替换为 `inner` 。
4. 打开 **SeeYue/CSS/code-block** 下的 `xxxx-theme.css` 文件，复制`nord.css`替换后的内容，重启 Typora，即可。

**Comment by Aurora-kite** [comment]
> 这与主题使用的代码配色和 Typora 自己使用的代码高亮语法有关。修改是比较麻烦的。可能你修改了这里，在别的编程语言里又出现了问题。
> 
> 或许你可以考虑换个代码配色，看看有没有让你满意的。更换主题代码配色的步骤如下：
> 
> 1. 访问 [CodeMirror: Theme Demo](https://codemirror.net/5/demo/theme.html) ，选择符合自己的主题。（以 nord 主题为例）
> 2. 下载主题代码文件 https://codemirror.net/5/codemirror.zip （**code-block** 文件夹已下载）
> 3. 打开 `nord.css` ，将代码内关键字 `nord` 替换为 `inner` 。
> 4. 打开 **SeeYue/CSS/code-block** 下的 `xxxx-theme.css` 文件，复制`nord.css`替换后的内容，重启 Typora，即可。

好吧，那是typora自己的问题

**Comment by Aurora-kite** [comment]
> > 这与主题使用的代码配色和 Typora 自己使用的代码高亮语法有关。修改是比较麻烦的。可能你修改了这里，在别的编程语言里又出现了问题。
> > 或许你可以考虑换个代码配色，看看有没有让你满意的。更换主题代码配色的步骤如下：
> > 
> > 1. 访问 [CodeMirror: Theme Demo](https://codemirror.net/5/demo/theme.html) ，选择符合自己的主题。（以 nord 主题为例）
> > 2. 下载主题代码文件 https://codemirror.net/5/codemirror.zip （**code-block** 文件夹已下载）
> > 3. 打开 `nord.css` ，将代码内关键字 `nord` 替换为 `inner` 。
> > 4. 打开 **SeeYue/CSS/code-block** 下的 `xxxx-theme.css` 文件，复制`nord.css`替换后的内容，重启 Typora，即可。
> 
> 好吧，那是typora自己的问题

问题可以关闭了，这是typora软件的问题，和主题无关🤔
