### ISSUE TITLE
导出html问题

### ISSUE THREAD

**Issue by 87zrjojo** [jinghu-moon/typora-see-yue-theme#45]
导出html时有些标题、任务列表等标识或图标不显示。比如导出时标题可有可以不显示标题等级，也显示不出来。任务列表- [x]不显示已完成样式√，还有块引用blockquotes挺好看的，但导出后也显示不出图标。不知怎么回事。

**Comment by jinghu-moon** [comment]
导出 HTML，字体引用就失效了。建议导出 PDF。这个暂时没法处理。抱歉
