### ISSUE TITLE
暗黑模式下引用中的代码块边缘看不清

### ISSUE THREAD

**Issue by hengxingstu** [jinghu-moon/typora-see-yue-theme#46]
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/49084129/491df324-1788-45d5-aa0a-50a8c6ad4ed8)
另外有一个小问题，C#的关键字`init`没有被高亮

**Comment by jinghu-moon** [comment]
**SeeYue/CSS/custom/** 路径下 `custom-pure.css` 文件，添加以下代码：

```css
blockquote pre {
  background-color: #111 !important;
}
```

后续版本会修复这个问题。

**代码高亮问题**

这与主题使用的代码配色和 Typora 自己使用的代码高亮语法有关。修改是比较麻烦的。可能你修改了这里，在别的编程语言里又出现了问题。

或许你可以考虑换个代码配色，看看有没有让你满意的。更换主题代码配色的步骤如下：

1. 访问 [CodeMirror: Theme Demo](https://codemirror.net/5/demo/theme.html) ，选择符合自己的主题。（以 nord 主题为例）
2. 下载主题代码文件 <https://codemirror.net/5/codemirror.zip> （**code-block** 文件夹已下载）
3. 打开 `nord.css` ，将代码内关键字 `nord` 替换为 `inner` 。
4. 打开 **SeeYue/CSS/code-block** 下的 `xxxx-theme.css` 文件，复制`nord.css`替换后的内容，重启 Typora，即可。

**Comment by hengxingstu** [comment]
感谢回答
