### ISSUE TITLE
Python代码块高亮问题

### ISSUE THREAD

**Issue by cfikt** [jinghu-moon/typora-see-yue-theme#47]
Python代码块中多行注释的颜色如何修改，颜色跟其它关键字相同，看代码很难受
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/109979597/9777a0f7-cb78-4227-8785-04093530a3d9)

**Comment by jinghu-moon** [comment]
这与主题使用的代码配色和 Typora 自己使用的代码高亮语法有关。修改是比较麻烦的。可能你修改了这里，在别的编程语言里又出现了问题。

或许你可以考虑换个代码配色，看看有没有让你满意的。更换主题代码配色的步骤如下：

1. 访问 CodeMirror: Theme Demo ，选择符合自己的主题。（以 nord 主题为例）
2. 下载主题代码文件 https://codemirror.net/5/codemirror.zip （code-block 文件夹已下载）
3. 打开 nord.css ，将代码内关键字 nord 替换为 inner 。
4. 打开 SeeYue/CSS/code-block 下的 xxxx-theme.css 文件，复制nord.css替换后的内容，重启 Typora，即可。

**Comment by jinghu-moon** [comment]
我去看了下，Typora 使用的代码编辑器组件没有把 Python 的多行注释识别出来。别的编程语言是可以识别出来的。如下图：

![](https://s3.bmp.ovh/imgs/2023/06/16/d9f575ca8da41d23.png)

C 语言有 cm-comment 选择器，Python 没有。

**Comment by cfikt** [comment]
在忽略别的编程语言中的问题的前提下，可以如何进行修改吗

**Comment by jinghu-moon** [comment]
看起来应该是不能修改了，没有 cm-comment 选择器，修改这部分内容，会影响别的内容。单行注释也会出现这种问题，等待官方修复吧 🙃
