### ISSUE TITLE
汉字“目”不清晰

### ISSUE THREAD

**Issue by Aurora-kite** [jinghu-moon/typora-see-yue-theme#49]
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/30ed1926-c198-480f-8b28-c47fc49dbb3b)
**如图，目录里面的“目”字第二横几乎没有**

**Comment by jinghu-moon** [comment]
嗯，在我的电脑显示挺清晰的嘛

![](https://s3.bmp.ovh/imgs/2023/06/29/788c0df9a2030ecd.png)

这个和电脑有关吧？或者你可以试着在 `xxxx-configs.css`文件里，修改目录里一级标题的大小

**Comment by jinghu-moon** [comment]
`xxxx-configs.css` 搜索 **--contents-h1-size**，修改这个。

**Comment by Aurora-kite** [comment]
> 嗯，在我的电脑显示挺清晰的嘛
> 
> ![](https://camo.githubusercontent.com/70b204423df0a9f8159ba2862dfa89f0de0076657bcfcf6a4b4f9728f4ed6e04/68747470733a2f2f73332e626d702e6f76682f696d67732f323032332f30362f32392f373838633064663961323033306563642e706e67)
> 
> 这个和电脑有关吧？或者你可以试着在 `xxxx-configs.css`文件里，修改目录里一级标题的大小

是目录里面除了一级标题**之外的标题**（蓝色字体），第二横几乎没有

**Comment by jinghu-moon** [comment]
不好意思，看错问题了。宋体就是这样的，字形比较纤细。换个高分辨率的屏幕，可能会好点。可以考虑使用别的字体或者直接用黑体，显示会清楚很多。这跟主题是没有关系的。

**Comment by Aurora-kite** [comment]
> 不好意思，看错问题了。宋体就是这样的，字形比较纤细。换个高分辨率的屏幕，可能会好点。可以考虑使用别的字体或者直接用黑体，显示会清楚很多。这跟主题是没有关系的。

好吧，问题已解决
