### ISSUE TITLE
关于高斯模糊

### ISSUE THREAD

**Issue by Soanguy** [jinghu-moon/typora-see-yue-theme#5]
对于高斯模糊后样式很丑的问题可以试着为其添加一个比较合适颜色的背景来防止因为图片太灰或太亮导致的无法观看。另外可以试着调整模糊度，降低模糊度可以带来比较好的效能。

```
background: rgb(213 223 225 / 50%);
backdrop-filter: blur(15px) saturate(0.5);
```

**Comment by jinghu-moon** [comment]
感谢老哥的建议。我的主题参考了你的 autumns 主题。在 v1.3 版本，我计划移除毛玻璃效果，增加背景图 / 背景色。详情请看  See Yue 主题开发计划： https://github.com/users/jinghu-moon/projects/1/views/1。v1.3 预计在下周三之前发布。

最近比较忙，才看到 issues。😑
