### ISSUE TITLE
自动换行能否实现sublime text那种换行效果

### ISSUE THREAD

**Issue by luceln** [jinghu-moon/typora-see-yue-theme#54]
sublime text的自动换行效果好多了，不会显示到行首，看着很清晰
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/62422565/79de5311-f63b-4f16-8689-a8f495dc7fc7)

typora的自动换行效果一言难尽。。。代码长了会显示到行首，显得很乱
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/62422565/a9a07f0d-a389-4bc4-8501-b14ecb41af3f)

大佬看看能不能实现这种显示效果

**Comment by jinghu-moon** [comment]
这段时间在考研复习。没关注 GitHub 的消息。抱歉。

单纯的 CSS 是无法实现的。使用 JS 应该可以。你可以在这个项目 https://github.com/obgnail/typora_plugin 提一个 issue，看看该作者能不能实现。
