### ISSUE TITLE
小圆点开启

### ISSUE THREAD

**Issue by Aurora-kite** [jinghu-moon/typora-see-yue-theme#55]
怎么设置开启三种颜色的小圆点，我看必须要二者同时启用才能完整呈现呀，为什么不能同时开启
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/32b336a2-91c4-47bf-a98f-a748e839145a)
 不过两个都开启后，小圆点和语言标识（右上角那个C）不在同一个水平线上
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/eb979749-58fe-415b-9ba1-1c1e89cb2471)

**Comment by jinghu-moon** [comment]
要显示代码块顶栏和编程语言，打开 `see-yue-xxxx.css` ，按如下操作。

```css
/* 14.1 代码块顶栏设置 */
@import "./SeeYue/CSS/code-block/top-bar.css";

/* 14.2 代码块显示代码语言 */
/* @import "./SeeYue/CSS/code-block/code-lang.css"; */

/* 14.3 代码块代码语言列表 */
@import "./SeeYue/CSS/code-block/code-lang-lists.css";

/* 14.4 代码块【浅色】配色设置 */
@import "./SeeYue/CSS/code-block/light-theme.css";
```

修改代码块顶栏左侧小圆点颜色，打开 `xxxx-config.css` ，搜索 **左侧小圆点**，按注释修改。

```css
  /* ============ 左侧小圆点 ============ */
  /* 阴影模拟小圆点 */
  /* 代码块顶栏左侧小圆点大小，用 width、height 实现 */
  --code-block-topBar-left-all-dot-size      : 10px;
  /* 代码块顶栏左侧红色小圆点颜色 */
  --code-block-topBar-left-redDot-color      : #ff5f5a;
  /* 代码块顶栏左侧黄色小圆点颜色 */
  --code-block-topBar-left-yellowDot-color   : #ffbe2e;
  /* 代码块顶栏左侧绿色小圆点颜色 */
  --code-block-topBar-left-greenDot-color    : #2aca44;
  /* 代码块顶栏左侧小圆点与小圆点间距 */
  --code-block-topBar-left-dots-distance     : 25px;
  /* 代码块顶栏左侧小圆点上下位置，top 实现 */
  --code-block-topBar-left-dots-top-position : -17px;
  /* 代码块顶栏左侧小圆点左右位置，left 实现 */
  --code-block-topBar-left-dots-left-position: 8px;
```

**Comment by Aurora-kite** [comment]
> 要显示代码块顶栏和编程语言，打开 `see-yue-xxxx.css` ，按如下操作。
> 
> ```css
> /* 14.1 代码块顶栏设置 */
> @import "./SeeYue/CSS/code-block/top-bar.css";
> 
> /* 14.2 代码块显示代码语言 */
> /* @import "./SeeYue/CSS/code-block/code-lang.css"; */
> 
> /* 14.3 代码块代码语言列表 */
> @import "./SeeYue/CSS/code-block/code-lang-lists.css";
> 
> /* 14.4 代码块【浅色】配色设置 */
> @import "./SeeYue/CSS/code-block/light-theme.css";
> ```
> 
> 修改代码块顶栏左侧小圆点颜色，打开 `xxxx-config.css` ，搜索 **左侧小圆点**，按注释修改。
> 
> ```css
>   /* ============ 左侧小圆点 ============ */
>   /* 阴影模拟小圆点 */
>   /* 代码块顶栏左侧小圆点大小，用 width、height 实现 */
>   --code-block-topBar-left-all-dot-size      : 10px;
>   /* 代码块顶栏左侧红色小圆点颜色 */
>   --code-block-topBar-left-redDot-color      : #ff5f5a;
>   /* 代码块顶栏左侧黄色小圆点颜色 */
>   --code-block-topBar-left-yellowDot-color   : #ffbe2e;
>   /* 代码块顶栏左侧绿色小圆点颜色 */
>   --code-block-topBar-left-greenDot-color    : #2aca44;
>   /* 代码块顶栏左侧小圆点与小圆点间距 */
>   --code-block-topBar-left-dots-distance     : 25px;
>   /* 代码块顶栏左侧小圆点上下位置，top 实现 */
>   --code-block-topBar-left-dots-top-position : -17px;
>   /* 代码块顶栏左侧小圆点左右位置，left 实现 */
>   --code-block-topBar-left-dots-left-position: 8px;
> ```
抱歉，我没有太理解你的意思,我再具体重述一下我的问题
1.在`see yue pure`主题下，小圆点和编程语言无法到同一个水平线上
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/b808db3c-e50d-4f68-abd9-c8cdcb704b97)

2.我希望像`see yue salt`这样的，小圆点和编程语言在同一个水平线上
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/1c906cdb-9844-4575-8ead-b84357b573b2)

**Comment by Aurora-kite** [comment]
问题已解决，注释掉`top-bar.css`即可
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/df6a24ac-349a-4463-b58a-0254506343ff)
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/0197b942-f2d9-4f39-8132-b69001c813f4)

**Comment by jinghu-moon** [comment]
> 问题已解决，注释掉`top-bar.css`即可 ![image](https://user-images.githubusercontent.com/85811651/278915225-df6a24ac-349a-4463-b58a-0254506343ff.png) ![image](https://user-images.githubusercontent.com/85811651/278915299-0197b942-f2d9-4f39-8132-b69001c813f4.png)

图片里不是注释了 `code-lang.css` 吗？`code-Lang.css`、`top-bar.css` 二者不能同时使用，可能你都使用了。自定义主题的时候，请多看看**主题说明（必看）.md**和 `xxxx-config.css` 内部说明。

**Comment by Aurora-kite** [comment]
> > 问题已解决，注释掉`top-bar.css`即可 ![image](https://user-images.githubusercontent.com/85811651/278915225-df6a24ac-349a-4463-b58a-0254506343ff.png) ![image](https://user-images.githubusercontent.com/85811651/278915299-0197b942-f2d9-4f39-8132-b69001c813f4.png)
> 
> 图片里不是注释了 `code-lang.css` 吗？`code-Lang.css`、`top-bar.css` 二者不能同时使用，可能你都使用了。自定义主题的时候，请多看看**主题说明（必看）.md**和 `xxxx-config.css` 内部说明。

sorry😭
