### ISSUE TITLE
HTML生成的表格显示有误

### ISSUE THREAD

**Issue by Aurora-kite** [jinghu-moon/typora-see-yue-theme#57]
# 使用HTML生成的表格有误，表现为边框不全（缺失表格边框）
## 大佬的`see-yue`主题下HTML表格显示🥰
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/bda37cff-2fc7-4c65-afb5-f6ab189db34e)
## `Typora`自带的`Github`主题下HTML表格显示
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/0308f577-385f-41d1-82b4-608a2289202c)
### HTML代码
```html
<table>
	<tr>
		<td>小王</td>
		<td>小小王</td>
	<tr>
	<tr>
		<td colspan="2">隔壁老王</td>
	<tr>
</table>
```
```html
<table>
	<tr>
		<td>车神</td>
		<td>名车</td>
	</tr>
	<tr>
		<td rowspan="2">隔壁老王</td>
		<td>自行车</td>
	</tr>
	<tr>
		<td>电瓶车</td>
	</tr>
</table>
```

```html
<table>
    <tr>
        <th>11</th><th>22</th><th>33</th>
    </tr>
    <tr>
        <td rowspan="3">1班</td><td>语文</td><td>95</td>
    </tr>
    <tr>
        <td>数学</td><td>96</td>
    </tr>
    <tr>
        <td>英语</td><td>92</td>
    </tr>
</table>
```

## 恳请大佬修复后的效果😘💕
**①修复边框，能显示完全
②表格的奇偶数行有不同底色**

**Comment by Aurora-kite** [comment]
## 补充一下其他两个主题的显示效果（皆为HTML生成的表格）😁
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/571cfde3-b947-4286-9ee1-59bddbd8cabc)
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/634f21dd-5dcc-4f7b-b74b-2d16d804dfdc)

**Comment by jinghu-moon** [comment]
问题 1：这个不好改。我的主题设置表格外边框是通过 `box-shadow` 实现的。你的 HTML 表格，我无法确认表格第一行、最后一行的形态，我就不能设置它的样式。

问题 2：奇偶数行颜色，在 `xxxx-config.css` 里搜索 **--table-tbody-oddNum-line-bg-color**，按提示修改。

**Comment by Aurora-kite** [comment]
> 问题 1：这个不好改。我的主题设置表格外边框是通过 `box-shadow` 实现的。你的 HTML 表格，我无法确认表格第一行、最后一行的形态，我就不能设置它的样式。
> 
>
问题 2：奇偶数行颜色，在 `xxxx-config.css` 里搜索 **--table-tbody-oddNum-line-bg-color**，按提示修改。
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/1276c101-9f97-4b07-862e-efaffb176a36)

那加上其他的CSS属性呢，比如`border`或者`outline `👀

**Comment by jinghu-moon** [comment]
使用 `border` 设置边框可以，但是这样的边框加上 `border-radius`，就是显得很难看（外边框宽度不一致，四个角显得略窄）。而使用 `box-shadow` 模拟边框不会出现这种情况。
