### ISSUE TITLE
代码块没有行号啊

### ISSUE THREAD

**Issue by jia1314521** [jinghu-moon/typora-see-yue-theme#59]
代码块就是不显示行号啊？
<a href="https://imgse.com/i/piT2f41"><img src="https://s11.ax1x.com/2023/12/22/piT2f41.png" alt="piT2f41.png" border="0" /></a>

**Comment by jinghu-moon** [comment]
主题版本是多少？是否在偏好设置 —> markdown —> 代码块，勾选显示代码块行号？

Typora v1.7.6，主题 v.1.4.0，可以显示代码块行号。
