### ISSUE TITLE
Mac 下打开毛玻璃后，左侧菜单无法上下滑动

### ISSUE THREAD

**Issue by magiceses** [jinghu-moon/typora-see-yue-theme#64]
Mac 下打开毛玻璃后，左侧菜单无法上下滑动

**Comment by jinghu-moon** [comment]
Windows 环境下，使用 Typora v1.8.10 + 主题最新版本 v1.4.0，开启毛玻璃效果，左侧菜单可以上下滑动。你可以试试把 Typora 和主题版本升级到最新版看看。由于我没有 Mac，导致我无法排查问题所在。你可以尝试自行修复或者不使用毛玻璃效果。抱歉 : (

**Comment by magiceses** [comment]
好吧，那先关了毛玻璃效果，多谢
