### ISSUE TITLE
mac代码块失去焦点后，默认还是会选中第一行

### ISSUE THREAD

**Issue by lllllmaster-lulllll** [jinghu-moon/typora-see-yue-theme#67]
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/26450306/09a47186-eb98-4f42-b3d0-f81934d1c7dd)
这种的需要如何修改

**Comment by jinghu-moon** [comment]
没看懂。请提供详细说明和复现步骤。

另外，如果你要在浅色主题下使用 midnight 代码主题的话，最好还是在 `see-yue-pure.css` 文件里面作如下修改：

```css
/* 14.4 代码块【浅色】配色设置 */
@import "./SeeYue/CSS/code-block/light-theme.css";
/* 改成如下 */
@import "./SeeYue/CSS/code-block/dark-theme.css";
```

**Comment by lllllmaster-lulllll** [comment]
> 没看懂。请提供详细说明和复现步骤。
> 
> 另外，如果你要在浅色主题下使用 midnight 代码主题的话，最好还是在 `see-yue-pure.css` 文件里面作如下修改：
> 
> ```css
> /* 14.4 代码块【浅色】配色设置 */
> @import "./SeeYue/CSS/code-block/light-theme.css";
> /* 改成如下 */
> @import "./SeeYue/CSS/code-block/dark-theme.css";
> ```

![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/26450306/146f9798-e1a2-46fc-b202-1a319d66e608)


> [![image](https://private-user-images.githubusercontent.com/26450306/318348202-09a47186-eb98-4f42-b3d0-f81934d1c7dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTM5NDQsIm5iZiI6MTcxMTk1MzY0NCwicGF0aCI6Ii8yNjQ1MDMwNi8zMTgzNDgyMDItMDlhNDcxODYtZWI5OC00ZjQyLWIzZDAtZjgxOTM0ZDFjN2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2NDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMTc3MmIzZTE1OTY3NzIwZDkwNjhhZjQ2M2Q4ZDQ1MzRjYzc5MDI3ZWFlNzY4ZDA5YjIxZjU3OTZmNmZiZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQxSOLa4kpJxx0xUnm09HoYdVTHFdnmP-ioeQ0snaVk)](javascript:void(0)) 这种的需要如何修改

这个如果还是看不明白的话，可以加我个微信吗  15624985823
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/26450306/3170c703-b547-4127-b91c-9d3655867ad0)

**Comment by jinghu-moon** [comment]
`dark-theme.css` 文件注释以下代码。

```css
/*<!--activeline-->*/
/* .cm-s-inner .CodeMirror-activeline-background {
  background: #253540;
} */
```

此外你是在**浅色主题**下使用的 midnight，会导致代码块样式有点问题，你可以在 SeeYue\CSS\configs\\`pure-config.css` 中，参考注释做些许调整。

**Comment by lllllmaster-lulllll** [comment]
可以了   感谢
