### ISSUE TITLE
右侧滑动条太细，不容易点到。

### ISSUE THREAD

**Issue by operations4304** [jinghu-moon/typora-see-yue-theme#68]
我一般使用Typora用缩小的窗口，所以鼠标很难选中右侧滑动条。

鼠标移动多了就变成左右拉升了，而使用鼠标中键移动内容，又不太准。

我想能不能弄成可变大小的，就是鼠标没有放在滑动条上面时，显示细条；当鼠标放在滑动条附近时，显示粗条。

谢谢！

**Comment by jinghu-moon** [comment]
> 我想能不能弄成可变大小的，就是鼠标没有放在滑动条上面时，显示细条；当鼠标放在滑动条附近时，显示粗条。

这个做不到。得使用 JS 才可以。你可以试试增大滚动条的默认宽度。假设使用 See Yue Pure 主题。

进入 SeeYue\CSS\configs\\`pure-config.css`，搜索 **--writeArea-scroll-thumb-width**，参考注释调整滚动条宽度。

**Comment by operations4304** [comment]
非常感谢，宽度变大以后方便多了！超好用，点赞！
