### ISSUE TITLE
侧边栏点击标题，跳转有误

### ISSUE THREAD

**Issue by dselegent** [jinghu-moon/typora-see-yue-theme#7]

**Comment by jinghu-moon** [comment]
好的，感谢反馈，下个版本修复。代码太多，还没有定位到 bug 代码。测试了下，似乎较大的 md 文件会触发这个 bug

**Comment by dselegent** [comment]
是那个侧边栏文件的，我注释掉就没有了

**Comment by jinghu-moon** [comment]
`sidebar.css`吗？我猜测，应该也是这个文件的代码有问题。

**Comment by jinghu-moon** [comment]
还有其他主题用起来不舒服的地方吗？

**Comment by jinghu-moon** [comment]
注释掉 `transition` 这一行，bug 解决。我想想该如何解决。（想保留这个 hover 动画）😑

![](https://s3.bmp.ovh/imgs/2022/07/23/d2b1f85478fc49ad.png)

**Comment by jinghu-moon** [comment]
还可以把 `transition` 这一行改为以下代码，基本可以解决这个 bug。

```css
transition      : background-color 0.3s ease;
```

**Comment by jinghu-moon** [comment]
v1.3.2 已发布，请及时更新。新版本已修复此 bug。 😉

我关闭 issues 了。

**Comment by dselegent** [comment]
期待暗黑模式版本
