### ISSUE TITLE
这方框是乱码吗

### ISSUE THREAD

**Issue by ishuliang** [jinghu-moon/typora-see-yue-theme#70]
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/105412844/ee7dba06-b878-43a1-a779-76dbc021509c)

**Comment by jinghu-moon** [comment]
看起来像是文字的问题，不是主题的问题。可以把这个 MD 文件发给我吗？我来排查一下。

**Comment by ishuliang** [comment]
[test.md](https://github.com/jinghu-moon/typora-see-yue-theme/files/15492388/test.md)
目录那一块，还有一级标题，二级标题在正文中也有一个

**Comment by jinghu-moon** [comment]
Typora v1.8.10 + SueYue 主题 v1.4.0，打开 **test.md**，没有出现乱码问题。你在我的环境条件下试试，看看还有没有乱码问题。

**Comment by ishuliang** [comment]
可以了，看来是版本问题，多谢多谢
