### ISSUE TITLE
Zhudou 字体下的英文单引号有机会出现过宽情况

### ISSUE THREAD

**Issue by zalexk** [jinghu-moon/typora-see-yue-theme#71]
在输入英文时，由于不明原因（可能是输入法原因），英文的单引号会出现类似全角引号的样式
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/124547242/a4c30c96-5ce6-438e-9e37-74a3ba6228e8)

之后我在 `pure-config.css` （其他主题也应该存在同样问题）中（`--writeArea-text-font  : "Zhudou", "HarmonyOS-Sans", "HarmonyOS-Regular";` ）删去 Zhudou 字体，便不会发生。
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/124547242/fd9de927-ad58-47d7-bc8c-8705f216fbbf)

**Comment by jinghu-moon** [comment]
![](https://s3.bmp.ovh/imgs/2024/07/01/b32baaaa9d7cd49d.png)

使用微软输入法，切换到英文输入状态，可以正常输入英文引号。

但是在 word/记事本 中输入 英文引号，复制到 Typora 中，就会变为中文的引号。

可能是 Typora 的问题或者 Zhudou 字体的问题。
