### ISSUE TITLE
颜色冲突，显示异常

### ISSUE THREAD

**Issue by OvOHaHaa** [jinghu-moon/typora-see-yue-theme#75]
<img width="1208" alt="图片" src="https://github.com/user-attachments/assets/38f8979e-4b22-4922-b4dc-87661f14fe02">
很多颜色冲突，导致看不清内容，特别是在win中一体化窗口下会隐藏掉很多ui。
请问还会更新修复吗？谢谢

**Comment by jinghu-moon** [comment]
年底前会更新解决的，工作了时间不多：（

**Comment by OvOHaHaa** [comment]
期待~~
